# docker-compose-test.yml
version: "3.8"
services:
  sut:
    image: voty
    build:
      context: ./
      dockerfile: Dockerfile.test
    env_file: ".env"
    # --ipc=host see https://github.com/cypress-io/cypress/issues/350
    #   add this if docker starts to crash on long-running test runs
    #ipc: host
    environment:
      - DATABASE_URL=postgres://voty:voty@postgres:5432/voty
      - CYPRESS_RECORD_KEY # pass on from GitHub-Actions or cmdline
      - GITHUB_TOKEN # pass on from GitHub-Actions or cmdline
      - NODE_ENV=test
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - postgres
    links:
      - postgres
    command: sh -c "sleep 2 && yarn run ci:test"

  postgres:
    image: "postgres:13-alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: voty
      POSTGRES_PASSWORD: voty
      POSTGRES_DB: voty
