# docker-compose-test.yml
version: "3.8"
services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://voty:voty@postgres:5432/voty
      NODE_ENV: production
      PORT: 3000
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3000:3000"
    env_file: ".env"
    command: sh -c "yarn run prisma && yarn start && yarn test"
    #volumes:
    #  - .:/app/
    #  - /app/

  postgres:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: voty
      POSTGRES_PASSWORD: voty
      POSTGRES_DB: voty
