# docker-compose-test.yml
version: "3.8"
services:
  sut:
    image: voty
    build: .
    env_file: ".env"
    environment:
      - DATABASE_URL=postgres://voty:voty@postgres:5432/voty
      - CYPRESS_RECORD_KEY # pass on from GitHub-Actions or cmdline
      - GITHUB_TOKEN # pass on from GitHub-Actions or cmdline
      - NODE_ENV=test
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - postgres
    links:
      - postgres
    command: /bin/sh wait-for-db.sh $DATABASE_URL -- yarn run ci:test

  postgres:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: voty
      POSTGRES_PASSWORD: voty
      POSTGRES_DB: voty
