# docker-compose-test.yml
version: "3.8"
services:
  sut:
    build:
      context: .
      dockerfile: "Dockerfile.test"
    environment:
      - DATABASE_URL=postgres://voty:voty@postgres:5432/voty
      - CYPRESS_RECORD_KEY
      - GITHUB_TOKEN
      - NODE_ENV=dev
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      - CYPRESS_BASEURL=http://app:3000/
      - CYPRESS_baseUrl=http://app:3000/
    depends_on:
      - app
    links:
      - app

  app:
    container_name: "app"
    build: .
    environment:
      - DATABASE_URL=postgres://voty:voty@postgres:5432/voty
      - NODE_ENV=dev
      - PORT=3000
      - INITDB=1 # not yet implemented
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    env_file: ".env"
    command: yarn start
    depends_on:
      - postgres
    links:
      - postgres
    #volumes:
    #  - .:/app/
    #  - /app/

  postgres:
    image: "postgres:12"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: voty
      POSTGRES_PASSWORD: voty
      POSTGRES_DB: voty
