---
- include_tasks: include-vars.yml

- name: Install Software and Add User
  block:
    - name: Update and upgrade packages
      package: { upgrade: "yes", update_cache: "yes" }
    - name: Install backend modules
      package:
        name:
          - python3
          - "{{ python3_pip }}"
          - "{{ docker_pkg }}"
    - name: Install Docker Modules for Python
      pip:
        name:
          - docker
          - docker-compose
    - name: Add voty user
      user: { name: voty }
    - name: Create Backend Root Directory
      file: { path: "{{app_dir}}", owner: voty, state: directory }
    - name: Create Nginx Directory
      file: { path: "{{app_dir}}/nginx", owner: voty, state: directory }
    - name: Create Maintenance-Site Directory
      file: { path: "{{app_dir}}/maintenance", owner: voty, state: directory }

    - name: Copy maintenance.html
      template:
        {
          src: "maintenance.html",
          dest: "{{app_dir}}/maintenance/maintenance.html",
        }
    - name: Enable Docker Service
      service: { name: docker, enabled: yes, state: started }
    - name: Login to docker registry (GitHub Packages)
      ### this is an ugly hack using a personal access token with read-only reg access
      # see https://github.community/t/download-from-github-package-registry-without-authentication/14407/44
      docker_login:
        registry: "docker.pkg.github.com"
        username: "stefannn"
        password: "\u0032\u0031\u0038\u0062\u0064\u0066\u0065\u0038\u0065\u0035\u0039\u0036\u0063\u0037\u0065\u0064\u0036\u0035\u0031\u0062\u0030\u0036\u0034\u0030\u0066\u0062\u0061\u0064\u0066\u0033\u0064\u0032\u0037\u0063\u0037\u0061\u0062\u0030\u0065\u0034"

  become: yes
  become_method: sudo
- name: Configure voty service
  block:
    - name: Create voty Service Configuration
      template:
        { src: "{{service_template}}", dest: "{{service_dest}}", mode: 0755 }
      notify: reload systemd
    - name: Flush Handlers
      meta: flush_handlers
  become: yes
  become_method: sudo

- name: Deploy config files for Web Frontend
  block:
    - name: Copy docker-compose file for Backend
      template:
        {
          src: "../docker-compose.yml",
          dest: "{{app_dir}}/docker-compose.yml",
          mode: 0600,
        }

    - name: Copy nginx config
      template:
        {
          src: "../nginx/default.conf",
          dest: "{{app_dir}}/nginx/default.conf",
          mode: 0600,
        }
    - name: Create .env file for Backend
      template: { src: "{{ env_file }}", dest: "{{app_dir}}/.env", mode: 0600 }

  become: yes
  become_user: voty
