---
- name: Install cron jobs on server
  block:
    - name: Create Backup Directory
      file: { path: "/voty/backup", owner: voty, state: directory }
    - name: Copy db backup script into cron.daily
      template:
        { src: db-backup, dest: "{{ cron_daily }}/db-backup", mode: "0700" }
  become: yes
  become_method: sudo
