---
- name: Pull latest version and restart server
  block:
    - name: Git Pull, update from Master
      command: docker exec app git -c http.https://github.com/.extraheader="" pull
    - name: Restart Voty App Container
      command: docker container restart app
  become: yes
  become_method: sudo
