---
- name: Pull and Deploy Docker Image
  block:
    - name: Clean up old docker files
      command: docker system prune -a -f
    - name: Pull and start docker compose
      #notify: restart voty
      docker_compose:
        pull: "yes"
        project_src: "{{app_dir}}"
        state: "present"
        restarted: yes

    - name: Enable Web Backend Service
      service: { name: voty, enabled: yes, state: restarted }
  become: yes
  become_method: sudo
