---
- hosts: web
  # if you install on a fresh host without python, you need to set gather_facts to "No"
  gather_facts: Yes
  pre_tasks:
    - name: "install python3"
      raw: "sudo apk add python3"
  become: yes
  vars:
    certbot_auto_renew_user: root
    certbot_auto_renew_minute: "0"
    certbot_auto_renew_hour: "5"
    certbot_admin_email: voty@teachen.ch
    certbot_create_if_missing: true
    certbot_package: certbot
    certbot_certs:
      - domains:
          - "{{ server_name }}"
          #- "www.{{server_name}}"

  tasks:
    - name: Include variables depending on OS distribution
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "vars/{{ansible_distribution}}.yml"
            - vars/Defaults.yaml
          paths:
            - "vars"

  roles:
    - role: common
      tags: common
    - role: ansible-role-certbot
      tags: cert
    - role: app
      tags: app
