---
- hosts: web
  # if you install on a fresh host without python, you need to set uncomment these lines
  # WATCH OUT: After the first run (which fails) you need to recomment it, otherwise it won't gather_facts
  #gather_facts: No
  #pre_tasks:
  #  - name: "install python3"
  #    raw: "sudo apk add python3"
  become: yes
  vars:
    certbot_auto_renew_user: root
    certbot_auto_renew_minute: "0"
    certbot_auto_renew_hour: "5"
    certbot_admin_email: voty@teachen.ch
    certbot_create_if_missing: true
    certbot_package: certbot
    certbot_certs:
      - domains:
          - "{{ server_name }}"
          - "www.{{server_name}}"
          - "{{old_server_name}}"
          - "www.{{old_server_name}}"

  tasks:
    - name: Include variables depending on OS distribution
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "Defaults.yml"

  roles:
    - role: ansible-role-certbot
      tags: cert
    - role: common
      tags: common
    - role: app
      tags: app
    - role: cron # this probably should only be in db role
      tags: cron
